# Introduction to NumPy & Creating Arrays.

In [2]:
# Convention for importing numpy 
import numpy as np

In [3]:
# Creating ndarray from Python list
list = [1,2,3,4,5]
#print(type(list))
ndarray = np.array(list)
print(ndarray)
#print(ndarray)

[1 2 3 4 5]


In [5]:
#.....
print(ndarray.shape)
print(ndarray.dtype)
print(ndarray.ndim)
print(ndarray.dtype)

(5,)
int32
1
int32


In [7]:
# Creating ndarray from two Python lists
lists = [[1,2,3,4,5],[6,7,8,9,10]] 
ndarray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(lists)
print(ndarray)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# inbuilt functions to initialize numpy
empty()
zeros()
ones()
full()
random.random()

In [15]:
# eexamples
scores = [2,1,4,5]
print("Random")
print(np.random.random(scores))
print("Full")
print(np.full(scores,4))
print("Ones")
print(np.ones(scores))
print("Zeros")
print(np.zeros(scores))
print("Empty")
print(np.empty(scores))

Random
[[[[0.05746705 0.29999946 0.50720503 0.54271468 0.17209173]
   [0.24825184 0.26973876 0.13815282 0.13165819 0.84512837]
   [0.22567792 0.93285179 0.00442882 0.01051654 0.0392976 ]
   [0.46194933 0.90527769 0.64958198 0.48133384 0.88999638]]]


 [[[0.85920619 0.1588139  0.32825617 0.85466787 0.23523375]
   [0.50216157 0.02991497 0.31574315 0.40458959 0.69678526]
   [0.48825736 0.58073211 0.08622627 0.22024386 0.41024577]
   [0.73865656 0.23163654 0.3162478  0.66471066 0.37479469]]]]
Full
[[[[4 4 4 4 4]
   [4 4 4 4 4]
   [4 4 4 4 4]
   [4 4 4 4 4]]]


 [[[4 4 4 4 4]
   [4 4 4 4 4]
   [4 4 4 4 4]
   [4 4 4 4 4]]]]
Ones
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
Zeros
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
Empty
[[[[0. 0. 0. 0. 0.]
   

# Intra-operability of Arrays and Scalars.

In [16]:
a = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
b = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])
print(a + b)
print(a * b)
print(5 / b)
print(a ** 2)

[[13. 13. 13.]
 [10. 10. 10.]]
[[36. 40. 42.]
 [ 9. 16. 21.]]
[[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]
[[81. 64. 49.]
 [ 1.  4.  9.]]


# Indexing With Arrays & Using Arrays for Data Processing

In [21]:
# Indexing Arrays
x = [1,2,3,4]
y = [5,6,7,8]
print(x[1])
print(y[1])
a_and_b = np.array([[2,4,6,8],[10,12,14,16]])
print(a_and_b[0,1],a_and_b[1,3])

2
6
4 16


In [22]:
# Slicing Arrays
a_and_b = np.array([[2,4,6,8],[10,12,14,16]])
print(a_and_b[1,0:2])
c_and_d = np.array([[18,20,22,24],[26,28,30,32],[34,36,38,40]])
print(c_and_d[:2, :1])

[10 12]
[[18]
 [26]]


In [23]:
# Advanced Methods 
# Integer Indexing
c_and_d = np.array([[18,20,22,24],[26,28,30,32],[34,36,38,40]])
print(c_and_d[[2,1,0],[3,2,1]])
# Boolean Indexing
c_and_d[c_and_d >= 30]

[40 30 20]


array([30, 32, 34, 36, 38, 40])

In [ ]:
# inbuilt mathematical functions
sum()
mean()
std()
coorcoef()
min()

# File Input and Output With Arrays

In [ ]:
#Numpy arrays can be loaded from and saved to binary files with .npy as the extension using load() and save() respectively. 
#This can also be done with text files using loadtxt() and savetxt().